/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.A5.SistemaOS.view;

import com.A5.SistemaOS.dao.ClienteDao;
import com.A5.SistemaOS.dao.OrdemServicoDao;
import com.A5.SistemaOS.model.Cliente;
import com.A5.SistemaOS.model.OrdemServico;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthu
 */
public class ChamadosAbertos extends javax.swing.JDialog {

    /**
     * Creates new form ChamadosAbertos2
     */

    private OrdemServicoDao oDao;

    private ClienteDao clienteDao;

    public ChamadosAbertos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsTabelaDB = new javax.swing.JScrollPane();
        jtTabelaDB = new javax.swing.JTable();
        jlPesquisaProtocolo = new javax.swing.JLabel();
        jtPesquisaProtocolo = new javax.swing.JTextField();
        jbPesquisaProtocolo = new javax.swing.JButton();
        jlPesquisaCpf = new javax.swing.JLabel();
        jtPesquisaCpf = new javax.swing.JTextField();
        jbPesquisaCpf = new javax.swing.JButton();
        jBNovoChamado = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(656, 360));
        setMinimumSize(new java.awt.Dimension(656, 360));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(63, 55, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(63, 55, 201));

        jtTabelaDB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtTabelaDB.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Cliente", "Descrição", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsTabelaDB.setViewportView(jtTabelaDB);

        jlPesquisaProtocolo.setText("Protocolo:");

        jbPesquisaProtocolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa2.png"))); // NOI18N
        jbPesquisaProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaProtocoloActionPerformed(evt);
            }
        });

        jlPesquisaCpf.setText("CPF:");

        jbPesquisaCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa2.png"))); // NOI18N
        jbPesquisaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaCpfActionPerformed(evt);
            }
        });

        jBNovoChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        jBNovoChamado.setText("Novo Chamado");
        jBNovoChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoChamadoActionPerformed(evt);
            }
        });

        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/alterar.png"))); // NOI18N
        jBEditar.setText("Abrir Chamado");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash.png"))); // NOI18N
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNovoChamado)
                .addGap(127, 127, 127)
                .addComponent(jBEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jsTabelaDB, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlPesquisaProtocolo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbPesquisaProtocolo)
                            .addGap(97, 97, 97)
                            .addComponent(jlPesquisaCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbPesquisaCpf)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNovoChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaProtocolo)
                            .addComponent(jtPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaCpf)
                            .addComponent(jtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jsTabelaDB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisaProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaProtocoloActionPerformed

            OrdemServico os = oDao.findByProtocolo(jtPesquisaProtocolo.getText());

            DefaultTableModel dftm = (DefaultTableModel) jtTabelaDB.getModel();

            while (dftm.getRowCount() > 0) {
                dftm.removeRow(0);
            }

            if (os.getFim() == null) {

                String[] linha = {os.getProtocolo(), os.getCliente().getNome(), os.getDescricao(), formataDataString(os.getInicio())};
                dftm.addRow(linha);
            }

    }//GEN-LAST:event_jbPesquisaProtocoloActionPerformed

    private void jbPesquisaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaCpfActionPerformed

            Cliente cliente = clienteDao.findByCpf(jtPesquisaCpf.getText());

            listaOS = oDao.findByClienteId(cliente.getId());

            prencherTabela(listaOS);

    }//GEN-LAST:event_jbPesquisaCpfActionPerformed

    private void jBNovoChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoChamadoActionPerformed

        NovoChamado novoChamado = new NovoChamado(null, true);

        novoChamado.setVisible(true);

        formWindowOpened(null);

    }//GEN-LAST:event_jBNovoChamadoActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed

        int row = jtTabelaDB.getSelectedRow();

        if (row <= -1) {

            JOptionPane.showMessageDialog(this, "Selecione um cliente!");

        } else {

            FecharChamado novaOs = new FecharChamado(null, true);

            novaOs.preparedEdit(listaOS.get(row));

            novaOs.setVisible(true);

            formWindowOpened(null);

        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        int row = jtTabelaDB.getSelectedRow();

        if (row <= -1) {

            JOptionPane.showMessageDialog(this, "Selecione uma OS!");

        } else {

            String senha = JOptionPane.showInputDialog("Senha mestra:");

            if (!senha.equals("123")) {

                JOptionPane.showMessageDialog(this, "Senha mestra incorreta!");

            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja apagar a Ordem de Serviço " + listaOS.get(row).getProtocolo() + "?",
                        "Apagar OS", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                        oDao.delete(listaOS.get(row));
                        JOptionPane.showMessageDialog(null, "OS apagada!");

                    formWindowOpened(null);
                }

            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

            listaOS = oDao.findAll();

            prencherTabela(listaOS);

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChamadosAbertos dialog = new ChamadosAbertos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovoChamado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbPesquisaCpf;
    private javax.swing.JButton jbPesquisaProtocolo;
    private javax.swing.JLabel jlPesquisaCpf;
    private javax.swing.JLabel jlPesquisaProtocolo;
    private javax.swing.JScrollPane jsTabelaDB;
    private javax.swing.JTextField jtPesquisaCpf;
    private javax.swing.JTextField jtPesquisaProtocolo;
    private javax.swing.JTable jtTabelaDB;
    // End of variables declaration//GEN-END:variables

    List<OrdemServico> listaOS;

    private void prencherTabela(List<OrdemServico> listaOS) {

        DefaultTableModel dftm = (DefaultTableModel) jtTabelaDB.getModel();

        while (dftm.getRowCount() > 0) {
            dftm.removeRow(0);
        }

        for (OrdemServico os : listaOS) {

            if (os.getFim() == null) {

                String[] linha = {os.getProtocolo(), os.getCliente().getNome(), os.getDescricao(), formataDataString(os.getInicio())};
                dftm.addRow(linha);

            }
        }

    }

    private String formataDataString(Timestamp tempo) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String formattedTimestamp = sdf.format(tempo);

        return formattedTimestamp;

    }

}
