/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.br.vianna.sistemaos.view;

import com.br.vianna.sistemaos.DAO.impl.ClienteDAO;
import com.br.vianna.sistemaos.DAO.impl.OrdemServicoDAO;
import com.br.vianna.sistemaos.model.Cliente;
import com.br.vianna.sistemaos.model.OrdemServico;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthu
 */
public class ChamadosFechados extends javax.swing.JDialog {

    /**
     * Creates new form ChamadosFechados2
     */
    public ChamadosFechados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlPesquisaProtocolo = new javax.swing.JLabel();
        jtPesquisaProtocolo = new javax.swing.JTextField();
        jbPesquisaProtocolo = new javax.swing.JButton();
        jlPesquisaCpf = new javax.swing.JLabel();
        jtPesquisaCpf = new javax.swing.JTextField();
        jbPesquisaCpf = new javax.swing.JButton();
        jsTabelaChamadoFechado = new javax.swing.JScrollPane();
        jtTabelaChamadoFechado = new javax.swing.JTable();
        jBConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(63, 55, 201));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(63, 55, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlPesquisaProtocolo.setText("Protocolo:");

        jbPesquisaProtocolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa2.png"))); // NOI18N
        jbPesquisaProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaProtocoloActionPerformed(evt);
            }
        });

        jlPesquisaCpf.setText("CPF:");

        jbPesquisaCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa2.png"))); // NOI18N
        jbPesquisaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaCpfActionPerformed(evt);
            }
        });

        jtTabelaChamadoFechado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtTabelaChamadoFechado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Cliente", "Descrição", "Início", "Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsTabelaChamadoFechado.setViewportView(jtTabelaChamadoFechado);

        jBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/consultar.png"))); // NOI18N
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jBConsultar)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jsTabelaChamadoFechado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlPesquisaProtocolo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbPesquisaProtocolo)
                            .addGap(97, 97, 97)
                            .addComponent(jlPesquisaCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbPesquisaCpf)
                            .addGap(0, 10, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaProtocolo)
                            .addComponent(jtPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaCpf)
                            .addComponent(jtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPesquisaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jsTabelaChamadoFechado, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {

            ArrayList<OrdemServico> listaOS = new OrdemServicoDAO().buscarTodos();

            listaOSCorreta = new ArrayList<>();

            for (OrdemServico os : listaOS) {

                if (os.getFim() != null) {

                    listaOSCorreta.add(os);

                }
            }

            prencherTabela(listaOSCorreta);

        } catch (ClassNotFoundException | SQLException ex) {

            JOptionPane.showMessageDialog(this, "Problema ao acessar o Banco de Dados");

        }
    }//GEN-LAST:event_formWindowOpened

    private void jbPesquisaProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaProtocoloActionPerformed

        try {

            OrdemServico os = new OrdemServicoDAO().buscarPorProtocolo(jtPesquisaProtocolo.getText());

            DefaultTableModel dftm = (DefaultTableModel) jtTabelaChamadoFechado.getModel();

            while (dftm.getRowCount() > 0) {
                dftm.removeRow(0);
            }

            if (os.getFim() != null) {

                String[] linha = {os.getProtocolo(), os.getCliente().getNome(), os.getDescricao(), formataDataString(os.getInicio())};
                dftm.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {

            JOptionPane.showMessageDialog(this, "Protocolo não encontado!");

        }

    }//GEN-LAST:event_jbPesquisaProtocoloActionPerformed

    private void jbPesquisaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaCpfActionPerformed

        try {

            Cliente cliente = new ClienteDAO().buscarPorCpf(jtPesquisaCpf.getText());

            listaOSCorreta = cliente.getListaOS();

            prencherTabela(listaOSCorreta);

        } catch (ClassNotFoundException | SQLException ex) {

            JOptionPane.showMessageDialog(this, "CPF não encontrado!");

        }

    }//GEN-LAST:event_jbPesquisaCpfActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        int row = jtTabelaChamadoFechado.getSelectedRow();

        if (row <= -1) {

            JOptionPane.showMessageDialog(this, "Selecione um cliente!");

        } else {

            OSConsulta consulta = new OSConsulta(null, true);

            consulta.preparedEdit(listaOSCorreta.get(row));

            consulta.setVisible(true);

            formWindowOpened(null);

        }

    }//GEN-LAST:event_jBConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadosFechados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadosFechados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadosFechados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadosFechados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChamadosFechados dialog = new ChamadosFechados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbPesquisaCpf;
    private javax.swing.JButton jbPesquisaProtocolo;
    private javax.swing.JLabel jlPesquisaCpf;
    private javax.swing.JLabel jlPesquisaProtocolo;
    private javax.swing.JScrollPane jsTabelaChamadoFechado;
    private javax.swing.JTextField jtPesquisaCpf;
    private javax.swing.JTextField jtPesquisaProtocolo;
    private javax.swing.JTable jtTabelaChamadoFechado;
    // End of variables declaration//GEN-END:variables

    ArrayList<OrdemServico> listaOSCorreta;

    private void prencherTabela(ArrayList<OrdemServico> listaOS) {

        DefaultTableModel dftm = (DefaultTableModel) jtTabelaChamadoFechado.getModel();

        while (dftm.getRowCount() > 0) {
            dftm.removeRow(0);
        }

        for (OrdemServico os : listaOS) {

            String[] linha = {os.getProtocolo(), os.getCliente().getNome(), os.getDescricao(), formataDataString(os.getInicio()), formataDataString(os.getFim())};
            dftm.addRow(linha);

        }

    }

    private String formataDataString(Timestamp tempo) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String formattedTimestamp = sdf.format(tempo);

        return formattedTimestamp;

    }

}
